title: Classes
modelClass: LTN\ElearningCourses\Models\ClassModel
list: $/ltn/elearningcourses/models/classmodel/columns.yaml
recordUrl: 'ltn/elearningcourses/classes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
