name: Classes
modelClass: LTN\ElearningCourses\Models\ClassModel
form: $/ltn/elearningcourses/models/classmodel/fields.yaml
defaultRedirect: ltn/elearningcourses/classes
create:
    redirect: 'ltn/elearningcourses/classes/update/:id'
    redirectClose: ltn/elearningcourses/classes
update:
    redirect: ltn/elearningcourses/classes
    redirectClose: ltn/elearningcourses/classes
preview: {  }
