title: 'ltn.elearningcourses::lang.course.manage_courses'
modelClass: LTN\ElearningCourses\Models\Course
list: $/ltn/elearningcourses/models/course/fullList.yaml
recordUrl: 'ltn/elearningcourses/courses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
