list: $/ltn/elearningcourses/models/blogpost/columns.yaml
modelClass: LTN\ElearningCourses\Models\BlogPost
title: BlogPosts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ltn/elearningcourses/blogposts/update/:id'
