title: Blog
modelClass: LTN\ElearningCourses\Models\BlogPost
list: $/ltn/elearningcourses/models/blogpost/columns.yaml
recordUrl: 'ltn/elearningcourses/blog/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
