title: Modules
modelClass: LTN\ElearningCourses\Models\Module
list: $/ltn/elearningcourses/models/module/columns.yaml
recordUrl: 'ltn/elearningcourses/modules/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
